AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotificationQueue
      VisibilityTimeout: 60
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt NotificationDLQ.Arn
        maxReceiveCount: 3
  
  NotificationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotificationDLQ
      VisibilityTimeout: 60
      MessageRetentionPeriod: 1209600 # 14 days
  
  # Secret used to resolve incoming webhook keys to actual webhook URLs
  GoogleWebhookSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: GoogleWebhookSecret
      Description: "Google Chat Webhook URL Secret"
  
  # Publisher Lambda that enqueues Google Chat messages
  PublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: publish_function/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          QUEUE_URL: !Ref NotificationQueue
      Policies: 
        - SQSSendMessagePolicy:
            QueueName: !GetAtt NotificationQueue.QueueName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /googlechat/notify
            Method: post

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notification_function/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          SECRET_ARN: !Ref GoogleWebhookSecret
          GOOGLE_CHAT_TIMEOUT: 5
          GOOGLE_CHAT_RETRIES: 2
          GOOGLE_CHAT_BACKOFF: 0.5
          SECRET_CACHE_TTL: 60
          DYNAMODB_TABLE_NAME: !Ref IdempotencyTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable
        - SQSPollerPolicy:
            QueueName: !GetAtt NotificationQueue.QueueName
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Ref GoogleWebhookSecret
      Events:
        NotificationEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NotificationQueue.Arn
            BatchSize: 10
            FunctionResponseTypes: 
              - ReportBatchItemFailures

  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GooglechatMessagesIdempotency
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
            
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
